#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

cd $PWD
find -type f -iname '*.jpg' | cut -c 3- | while read i
do
	JPEG=$(file "$i" | grep -o JPEG)
	if [ "$JPEG" = "JPEG" ]
	then
	    HASH=$(md5sum "$i" | cut -c -6)
	    if [ -e $HASH.jpg ]
	    then
		echo "ya existe el archivo" $HASH.jpg
	    else
		mv -vi "$i" $HASH.jpg
	    fi
		
		identify $HASH.jpg 2>/dev/null
		OK=$(echo $?)
		if [ $OK -gt 0 ]
		then
			echo "No es un JPEG válido" $HASH.jpg
			mv -vi $HASH.jpg $HASH.dat
		fi
	else
		echo "No es un JPEG" "$i"
		mv -vi "$i" "$i.dat"
	fi
done

jhead -n%Y-%m-%d-%H%M-%f *.jpg

